### ISSUE TITLE
El prefijo vejs- parece redundante, no creen?

### ISSUE THREAD

**Issue by stefanmaric** [vzlajs/press-kit#1]

**Comment by Villanuevand** [comment]
Se utilizó cómo marca visual al momento de hacer fork, identificarlos. Pero al realizar esta acción, se nuestra el usuario de origen. 

Así que creo que es válido tu planteamiento @stefanmaric 
Podríamos usar los prefijos para identificar, "grupos de trabajo" o algo así.

**Comment by Villanuevand** [comment]
Aceptado las recomendaciones @stefanmari, gracias por tu contribución.
