### ISSUE TITLE
Compartir enlace de videotutorial.

### ISSUE THREAD

**Issue by Villanuevand** [vzlajs/press-kit#2]
Hola muy buenas tardes comunidad.
Uno de nuestros miembros, Gilberto Trujillo [@gilberto_286](https://web.telegram.org/#/im?p=%40gilberto_286), quiere compartir un recurso para todos los que están comenzando con #Javascript. Gilberto, actualmente no posee cuenta en Github (ya está en proceso de abrir una).

@abr4xas  Podemos envíar por las redes sociales este videotutorial? 
Quedo atento.

**Comment by abr4xas** [comment]
Claro :D

**Comment by Villanuevand** [comment]
Gracias @abr4xas , entonces podemos dar por finalizado este issue.
